# Proyecto: Impacto de la Inteligencia Artificial en el Empleo (Hacia 2030)

## Problemática

La rápida adopción de la Inteligencia Artificial (IA) está transformando los entornos laborales. Si bien optimiza la productividad y la eficiencia, también genera una profunda incertidumbre sobre el futuro del empleo y la automatización de funciones.

El desafío principal radica en que **el impacto no es uniforme**: varía significativamente según el perfil de cada ocupación.

## La pregunta orientadora que guía el proyecto es:
 ¿Cómo podría impactar la adopción de la Inteligencia Artificial en las distintas ocupaciones laborales hacia el año 2030 de acuerdo con las variables contenidas en el dataset seleccionado? 

### El Desafío Analítico
La problemática de este proyecto consiste en **identificar y analizar qué factores clave determinan el nivel de riesgo de transformación laboral** frente a la IA hacia el año 2030. 

Para resolverlo, utilizaremos el conjunto de datos "AI Impact on Jobs 2030" disponible en Kaggle con el fin de evaluar cómo interactúan las siguientes variables:

* **Exposición tecnológica** y probabilidad de automatización.
* **Nivel educacional** requerido.
* **Experiencia laboral** previa.

**Objetivo del Notebook:** Encontrar los patrones ocultos que nos permitan comprender qué ocupaciones están más vulnerables y cuáles están más protegidas ante esta transición tecnológica.

### Carga del Dataset

En la siguiente celda se ejecuta el código que lee el archivo csv y lo carga a un objeto de tipo DataFrame del paquete Pandas. Además, se muestra la cantidad de registros del Dataset y la cantidad de variables incluidas, junto al nombre y tipo de dato de las caracteristicas (variable)

### Información de atributos
1. Variables principales
* **Job_Title Categórica (Nominal) Nombre de la ocupación
* **Average_Salary Numérica (int) Salario promedio anual 
* **Years_Experience Numérica (int) Años de experiencia laboral 
* **Education_Level Categórica Nivel educativo

2. Variables relacionadas con IA y Automatización
* **AI_Exposure_Index Numérica (float 0–1) Nivel de exposición del trabajo a la IA 
* **Tech_Growth_Factor Numérica (int) Tasa de crecimiento tecnológico del sector 
* **Automation_Probability_2030 Numérica (float 0–1) Probabilidad estimada de automatización hacia 2030
* **Risk_Category Categórica Nivel Riesgo de automatización: Low, Medium, High

3. Variables de habilidades (skills)
* **Skill_1 – Skill_10 Numéricas (float 0–1) Representan niveles de dominio en distintas habilidades (normalizadas). Cada columna corresponde a una habilidad específica del rol

In [203]:
import sys
import os
import importlib
import pandas as pd

#Impotar herramientas de preprocesamiento
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# subir un nivel y entrar a src"
ruta = os.path.abspath("../src")
sys.path.append(ruta)
    
# llamada funcion carga de datos dataset
from data_loading import cargar_datos

# llamada funciones de limpieza de datos
from preprocessing import limpiar_datos

#llamada funcion de caracterización de datos   
#from features import crear_features

#llamada funcion de entrenamiento del modelo
#from modeling import entrenar_modelo

#llamada funcion de evaluación del modelo

#from evaluation import evaluar_modelo

# 1. Carga Datos - ejecución funcion cargar datos y retorno dataset
ds = cargar_datos('../data/raw/AI_Impact_on_Jobs_2030.csv')

# 2. Limpieza de datos - ejecución funcion limpiar datos y retorno dataset limpio
#ds = limpiar_datos(ds)

# 3. Feature engineering - ejecución funcion crear features y retorno dataset con nuevas features
#ds = crear_features(ds)

# 4. Modelo - ejecución funcion entrenar modelo y retorno modelo entrenado
#model, X_test, y_test = entrenar_modelo(ds)


# 5. Evaluación - ejecución funcion evaluar modelo y retorno modelo evaluado
#evaluar_modelo(model, X_test, y_test)
ds

,Job_Title,Average_Salary,Years_Experience,Education_Level,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030,Risk_Category,Skill_1,Skill_2,Skill_3,Skill_4,Skill_5,Skill_6,Skill_7,Skill_8,Skill_9,Skill_10
0,Security Guard,45795,28,Master's,0.18,1.28,0.85,High,0.45,0.10,0.46,0.33,0.14,0.65,0.06,0.72,0.94,0.00
1,Research Scientist,133355,20,PhD,0.62,1.11,0.05,Low,0.02,0.52,0.40,0.05,0.97,0.23,0.09,0.62,0.38,0.98
2,Construction Worker,146216,2,High School,0.86,1.18,0.81,High,0.01,0.94,0.56,0.39,0.02,0.23,0.24,0.68,0.61,0.83
3,Software Engineer,136530,13,PhD,0.39,0.68,0.60,Medium,0.43,0.21,0.57,0.03,0.84,0.45,0.40,0.93,0.73,0.33
4,Financial Analyst,70397,22,High School,0.52,1.46,0.64,Medium,0.75,0.54,0.59,0.97,0.61,0.28,0.30,0.17,0.02,0.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Doctor,111319,6,Bachelor's,0.24,1.18,0.20,Low,0.73,0.37,0.99,0.07,0.08,0.92,0.65,0.33,0.76,0.45
2996,UX Researcher,44363,29,PhD,0.65,0.74,0.35,Medium,0.23,0.48,0.05,0.88,0.56,0.29,0.69,0.80,0.61,0.20
2997,Data Scientist,61325,23,Master's,0.64,0.94,0.39,Medium,0.28,0.62,0.73,0.21,0.96,0.01,0.70,0.29,0.48,0.57
2998,Graphic Designer,110296,7,PhD,0.95,1.23,0.46,Medium,0.21,0.18,0.14,0.22,0.55,0.68,0.31,0.55,0.34,0.70
2999,Graphic Designer,123909,25,PhD,0.69,0.56,0.49,Medium,0.77,0.54,0.95,0.05,0.29,0.22,0.77,0.52,0.14,0.29

#Pre procesamiento de datos
## Conversion de datos de atritbuto Job_Title
 Convertir valores string en valores numericos. Utilizando Label encoding y One hot encoding.
 Corregir valores nulos o faltantes. Utilizando imputacion de datos.

 Convertir valores string en valores numericos. Utilizando Label encoding (Ordinal) y One hot encoding (Nominal)
* **Corregir Atributo Job_Title** 
* Tipo variable categorica nominal [Software Engineer, Teacher, Nurse, Data Scientist, etc]
* Decision tecnica del metodo para utilizar  OneHotEncoder

In [ ]:
# llamada funciones de limpieza de datos
#import importlib
#import preprocessing

#importlib.reload(preprocessing)

#from preprocessing import encoding_categorico
#ds = encoding_categorico(ds)

#ds

#Paso 1 - Se crea una herramienta (un objeto) llamada le1 que sabe convertir categorías de texto en números enteros
le1 = LabelEncoder()

#Paso 2 - Se le da a la herramienta le1 los datos de la columna 'Job_Title' para que aprenda a convertir cada categoría en un número entero
data1 = ds['Job_Title']

#Paso 3 —  La herramienta aprende qué categorías distintas existen en la columna
le1.fit(data1)

#Paso 4 — data_transformada1 Ahora aplica lo aprendido: reemplaza cada texto por su número.
data_transformada1 = le1.transform(data1)
data_transformada1.reshape(-1,1)

#Paso 5  data_transformada1 Guarda esos números de vuelta en la columna original del DataFrame
ds['Job_Title'] = data_transformada1

#Paso 6 Se crea una segunda herramienta, ohe, esta vez para el One Hot Encoding.
ohe = OneHotEncoder()

#Paso 7 Se reorganizan los datos de una fila a una columna.
d1 = data_transformada1.reshape(-1,1)
ohe.fit(d1)
data_nueva1 = ohe.transform(d1).toarray()
data_nueva1 = pd.DataFrame(data_nueva1)
ds=pd.concat([ds, data_nueva1], axis=1)


# Obtener nombres correctos deseados, orden debe coincidir con las categorías detectadas
new_names = [ 'Security Guard', 'Research Scientist', 'Construction Worker','Software Engineer', 'Financial Analyst', 'AI Engineer', 'Mechanic', 'Teacher', 'HR Specialist', 'Customer Support', 'UX Researcher', 'Lawyer', 'Data Scientist', 'Graphic Designer', 'Retail Worker', 'Doctor', 'Truck Driver', 'Chef', 'Marketing Manager', 'Nurse']  

# Crear diccionario para renombrar
rename_dict = {i: new_names[i] for i in range(len(new_names))}

# Renombrar columnas en el DataFrame
ds.rename(columns=rename_dict, inplace=True)

ds

,Average_Salary,Years_Experience,Education_Level,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030,Risk_Category,Skill_1,Skill_2,Skill_3,...,Job_Title_Marketing Manager,Job_Title_Mechanic,Job_Title_Nurse,Job_Title_Research Scientist,Job_Title_Retail Worker,Job_Title_Security Guard,Job_Title_Software Engineer,Job_Title_Teacher,Job_Title_Truck Driver,Job_Title_UX Researcher
0,45795,28,2,0.18,1.28,0.85,2,0.45,0.10,0.46,...,False,False,False,False,False,True,False,False,False,False
1,133355,20,3,0.62,1.11,0.05,0,0.02,0.52,0.40,...,False,False,False,True,False,False,False,False,False,False
2,146216,2,0,0.86,1.18,0.81,2,0.01,0.94,0.56,...,False,False,False,False,False,False,False,False,False,False
3,136530,13,3,0.39,0.68,0.60,1,0.43,0.21,0.57,...,False,False,False,False,False,False,True,False,False,False
4,70397,22,0,0.52,1.46,0.64,1,0.75,0.54,0.59,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,111319,6,1,0.24,1.18,0.20,0,0.73,0.37,0.99,...,False,False,False,False,False,False,False,False,False,False
2996,44363,29,3,0.65,0.74,0.35,1,0.23,0.48,0.05,...,False,False,False,False,False,False,False,False,False,True
2997,61325,23,2,0.64,0.94,0.39,1,0.28,0.62,0.73,...,False,False,False,False,False,False,False,False,False,False
2998,110296,7,3,0.95,1.23,0.46,1,0.21,0.18,0.14,...,False,False,False,False,False,False,False,False,False,False
2999,123909,25,3,0.69,0.56,0.49,1,0.77,0.54,0.95,...,False,False,False,False,False,False,False,False,False,False

#pre procesamiento de datos
## Conversion de datos de atritbuto Risk_Category
 Convertir valores string en valores numericos. Utilizando Label encoding y One hot encoding.
 Corregir valores nulos o faltantes. Utilizando imputacion de datos.

 Convertir valores string en valores numericos. Utilizando Label encoding (Ordinal) y One hot encoding (Nominal)
* **Corregir Atributo Risk_Category** 
* Tipo variable categorica Ordinal ['Low', 'Medium', 'High']
* Decision tecnica del metodo para utilizar  OneHotEncoder

In [205]:
#Paso 1 - Se crea una herramienta (un objeto) llamada le1 que sabe convertir categorías de texto en números enteros
le1 = LabelEncoder()

#Paso 2 - Se le da a la herramienta le1 los datos de la columna 'Education_Level' para que aprenda a convertir cada categoría en un número entero
data1 = ds['Risk_Category']

#Paso 3 —  La herramienta aprende qué categorías distintas existen en la columna
le1.fit(data1)

#Paso 4 — data_transformada1 Ahora aplica lo aprendido: reemplaza cada texto por su número.
data_transformada1 = le1.transform(data1)
data_transformada1.reshape(-1,1)

#Paso 5  data_transformada1 Guarda esos números de vuelta en la columna original del DataFrame
ds['Risk_Category'] = data_transformada1

#Paso 6 Se crea una segunda herramienta, ohe, esta vez para el One Hot Encoding.
ohe = OneHotEncoder()

#Paso 7 Se reorganizan los datos de una fila a una columna.
d1 = data_transformada1.reshape(-1,1)
ohe.fit(d1)
data_nueva1 = ohe.transform(d1).toarray()
data_nueva1 = pd.DataFrame(data_nueva1)
ds=pd.concat([ds, data_nueva1], axis=1)


# Obtener nombres correctos deseados
new_names = ['Low', 'Medium', 'High']  # Orden debe coincidir con las categorías detectadas

# Crear diccionario para renombrar
rename_dict = {i: new_names[i] for i in range(len(new_names))}

# Renombrar columnas en el DataFrame
ds.rename(columns=rename_dict, inplace=True)

ds

,Average_Salary,Years_Experience,Education_Level,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030,Risk_Category,Skill_1,Skill_2,Skill_3,...,Job_Title_Research Scientist,Job_Title_Retail Worker,Job_Title_Security Guard,Job_Title_Software Engineer,Job_Title_Teacher,Job_Title_Truck Driver,Job_Title_UX Researcher,Low,Medium,High
0,45795,28,2,0.18,1.28,0.85,2,0.45,0.10,0.46,...,False,False,True,False,False,False,False,0.0,0.0,1.0
1,133355,20,3,0.62,1.11,0.05,0,0.02,0.52,0.40,...,True,False,False,False,False,False,False,1.0,0.0,0.0
2,146216,2,0,0.86,1.18,0.81,2,0.01,0.94,0.56,...,False,False,False,False,False,False,False,0.0,0.0,1.0
3,136530,13,3,0.39,0.68,0.60,1,0.43,0.21,0.57,...,False,False,False,True,False,False,False,0.0,1.0,0.0
4,70397,22,0,0.52,1.46,0.64,1,0.75,0.54,0.59,...,False,False,False,False,False,False,False,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,111319,6,1,0.24,1.18,0.20,0,0.73,0.37,0.99,...,False,False,False,False,False,False,False,1.0,0.0,0.0
2996,44363,29,3,0.65,0.74,0.35,1,0.23,0.48,0.05,...,False,False,False,False,False,False,True,0.0,1.0,0.0
2997,61325,23,2,0.64,0.94,0.39,1,0.28,0.62,0.73,...,False,False,False,False,False,False,False,0.0,1.0,0.0
2998,110296,7,3,0.95,1.23,0.46,1,0.21,0.18,0.14,...,False,False,False,False,False,False,False,0.0,1.0,0.0
2999,123909,25,3,0.69,0.56,0.49,1,0.77,0.54,0.95,...,False,False,False,False,False,False,False,0.0,1.0,0.0

#pre procesamiento de datos
## Conversion de datos de atritbuto Education_Level
 Convertir valores string en valores numericos. Utilizando Label encoding y One hot encoding.
 Corregir valores nulos o faltantes. Utilizando imputacion de datos.

 Convertir valores string en valores numericos. Utilizando Label encoding (Ordinal) y One hot encoding (Nominal)
* **Corregir Atributo Education_Level** 
* Tipo variable categorica Ordinal ['High School', "Bachelor's", "Master's", 'PhD']
* Decision tecnica del metodo para utilizar  OneHotEncoder

In [206]:
#Paso 1 - Se crea una herramienta (un objeto) llamada le1 que sabe convertir categorías de texto en números enteros
le1 = LabelEncoder()

#Paso 2 - Se le da a la herramienta le1 los datos de la columna 'Education_Level' para que aprenda a convertir cada categoría en un número entero
data1 = ds['Education_Level']

#Paso 3 —  La herramienta aprende qué categorías distintas existen en la columna
le1.fit(data1)

#Paso 4 — data_transformada1 Ahora aplica lo aprendido: reemplaza cada texto por su número.
data_transformada1 = le1.transform(data1)
data_transformada1.reshape(-1,1)

#Paso 5  data_transformada1 Guarda esos números de vuelta en la columna original del DataFrame
ds['Education_Level'] = data_transformada1

#Paso 6 Se crea una segunda herramienta, ohe, esta vez para el One Hot Encoding.
ohe = OneHotEncoder()

#Paso 7 Se reorganizan los datos de una fila a una columna.
d1 = data_transformada1.reshape(-1,1)
ohe.fit(d1)
data_nueva1 = ohe.transform(d1).toarray()
data_nueva1 = pd.DataFrame(data_nueva1)
ds=pd.concat([ds, data_nueva1], axis=1)


# Obtener nombres correctos deseados
new_names = ['Low', 'Medium', 'High']  # Orden debe coincidir con las categorías detectadas

# Crear diccionario para renombrar
rename_dict = {i: new_names[i] for i in range(len(new_names))}

# Renombrar columnas en el DataFrame
ds.rename(columns=rename_dict, inplace=True)

ds

,Average_Salary,Years_Experience,Education_Level,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030,Risk_Category,Skill_1,Skill_2,Skill_3,...,Job_Title_Teacher,Job_Title_Truck Driver,Job_Title_UX Researcher,Low,Medium,High,Low,Medium,High,3
0,45795,28,2,0.18,1.28,0.85,2,0.45,0.10,0.46,...,False,False,False,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,133355,20,3,0.62,1.11,0.05,0,0.02,0.52,0.40,...,False,False,False,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,146216,2,0,0.86,1.18,0.81,2,0.01,0.94,0.56,...,False,False,False,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,136530,13,3,0.39,0.68,0.60,1,0.43,0.21,0.57,...,False,False,False,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,70397,22,0,0.52,1.46,0.64,1,0.75,0.54,0.59,...,False,False,False,0.0,1.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,111319,6,1,0.24,1.18,0.20,0,0.73,0.37,0.99,...,False,False,False,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2996,44363,29,3,0.65,0.74,0.35,1,0.23,0.48,0.05,...,False,False,True,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2997,61325,23,2,0.64,0.94,0.39,1,0.28,0.62,0.73,...,False,False,False,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2998,110296,7,3,0.95,1.23,0.46,1,0.21,0.18,0.14,...,False,False,False,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2999,123909,25,3,0.69,0.56,0.49,1,0.77,0.54,0.95,...,False,False,False,0.0,1.0,0.0,0.0,0.0,0.0,1.0

### Limpieza y duplicados del data set

In [207]:
assert ds.isnull().sum().sum() == 0, "El dataset tiene valores nulos"

assert ds.duplicated().sum() == 0, "Existen registros duplicados"
#print("Nulos:", ds.isnull().sum().sum())
#print("Duplicados:", ds.duplicated().sum())

 ### Exportar dataset limpio a data/processed/

 * ** Guardar archivo ds.to_csv('../data/processed/AI_Impact_on_Jobs_2030_clean.csv', index=False)

In [208]:
#Formato estándar para pipelines de data science,  index=False → no guarda el índice
ds.to_csv('../data/processed/AI_Impact_on_Jobs_2030_clean.csv', index=False)

# Descripción de la estructura final del dataset limpio
print("=== ESTRUCTURA FINAL DEL DATASET ===")
print("\nNúmero de filas:", ds.shape[0])
print("Número de columnas:", ds.shape[1])
print("\nColumnas:")
print(ds.columns.tolist())
print("\nTipos de datos:")
print(ds.dtypes)
print("\nValores nulos:")
print(ds.isnull().sum())



#print("NA:", ds.isnull().sum().sum())
#print("Duplicados:", ds.duplicated().sum())
#print(ds.describe())

#ds.head()

#import matplotlib.pyplot as plt
#ds.boxplot(figsize=(12, 6))
#plt.show()

#print(ds.shape)
#print(ds.dtypes)
#ds
#print(ds.info())
#print(ds.describe())

=== ESTRUCTURA FINAL DEL DATASET ===

Número de filas: 3000
Número de columnas: 44

Columnas:
['Average_Salary', 'Years_Experience', 'Education_Level', 'AI_Exposure_Index', 'Tech_Growth_Factor', 'Automation_Probability_2030', 'Risk_Category', 'Skill_1', 'Skill_2', 'Skill_3', 'Skill_4', 'Skill_5', 'Skill_6', 'Skill_7', 'Skill_8', 'Skill_9', 'Skill_10', 'Job_Title_AI Engineer', 'Job_Title_Chef', 'Job_Title_Construction Worker', 'Job_Title_Customer Support', 'Job_Title_Data Scientist', 'Job_Title_Doctor', 'Job_Title_Financial Analyst', 'Job_Title_Graphic Designer', 'Job_Title_HR Specialist', 'Job_Title_Lawyer', 'Job_Title_Marketing Manager', 'Job_Title_Mechanic', 'Job_Title_Nurse', 'Job_Title_Research Scientist', 'Job_Title_Retail Worker', 'Job_Title_Security Guard', 'Job_Title_Software Engineer', 'Job_Title_Teacher', 'Job_Title_Truck Driver', 'Job_Title_UX Researcher', 'Low', 'Medium', 'High', 'Low', 'Medium', 'High', 3]

Tipos de datos:
Average_Salary                     int64
Years_Experience                   int64
Education_Level                    int64
AI_Exposure_Index                float64
Tech_Growth_Factor               float64
Automation_Probability_2030      float64
Risk_Category                      int64
Skill_1                          float64
Skill_2                          float64
Skill_3                          float64
Skill_4                          float64
Skill_5                          float64
Skill_6                          float64
Skill_7                          float64
Skill_8                          float64
Skill_9                          float64
Skill_10                         float64
Job_Title_AI Engineer               bool
Job_Title_Chef                      bool
Job_Title_Construction Worker       bool
Job_Title_Customer Support          bool
Job_Title_Data Scientist            bool
Job_Title_Doctor                    bool
Job_Title_Financial Analyst         bool
Job_Title_Graphic Designer          bool
Job_Title_HR Specialist             bool
Job_Title_Lawyer                    bool
Job_Title_Marketing Manager         bool
Job_Title_Mechanic                  bool
Job_Title_Nurse                     bool
Job_Title_Research Scientist        bool
Job_Title_Retail Worker             bool
Job_Title_Security Guard            bool
Job_Title_Software Engineer         bool
Job_Title_Teacher                   bool
Job_Title_Truck Driver              bool
Job_Title_UX Researcher             bool
Low                              float64
Medium                           float64
High                             float64
Low                              float64
Medium                           float64
High                             float64
3                                float64
dtype: object

Valores nulos:
Average_Salary                   0
Years_Experience                 0
Education_Level                  0
AI_Exposure_Index                0
Tech_Growth_Factor               0
Automation_Probability_2030      0
Risk_Category                    0
Skill_1                          0
Skill_2                          0
Skill_3                          0
Skill_4                          0
Skill_5                          0
Skill_6                          0
Skill_7                          0
Skill_8                          0
Skill_9                          0
Skill_10                         0
Job_Title_AI Engineer            0
Job_Title_Chef                   0
Job_Title_Construction Worker    0
Job_Title_Customer Support       0
Job_Title_Data Scientist         0
Job_Title_Doctor                 0
Job_Title_Financial Analyst      0
Job_Title_Graphic Designer       0
Job_Title_HR Specialist          0
Job_Title_Lawyer                 0
Job_Title_Marketing Manager      0
Job_Title_Mechanic               0
Job_Title_Nurse                  0
Job_Title_Research Scientist     0
Job_Title_Retail Worker          0
Job_Title_Security Guard         0
Job_Title_Software Engineer      0
Job_Title_Teacher                0
Job_Title_Truck Driver           0
Job_Title_UX Researcher          0
Low                              0
Medium                           0
High                             0
Low                              0
Medium                           0
High                             0
3                                0
dtype: int64